### ISSUE TITLE
TensorFlow Issue

### ISSUE THREAD

**Issue by RohaanA** [yastrebksv/TennisProject#1]
Hi,

I was attempting to run this project on Google Colab (GPU Runtime).

After install all the dependencies (I am using Python 3.6), I run into this error while running the model.

`RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

After a bit of a google search, apparently this happens when the data is on the CPU while the model is on the GPU. (I did not face this issue in colab CPU mode but the speed was terribly slow)

**Comment by RohaanA** [comment]
`
        self.model.to(self.device)
        self.model = self.model.to(self.device)
`

Adding these two lines after line 17 in ball_detector.py seems to have resolved the issue

**Comment by RohaanA** [comment]
After fixing the above errror, the ball detection went fine but during court detection, after about 15 min of waiting it runs into this error.
```

court detection
  0% 0/221 [00:00<?, ?it/s]/usr/local/envs/myenv/lib/python3.6/site-packages/torch/nn/functional.py:1569: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
 62% 138/221 [14:28<09:42,  7.02s/it]Traceback (most recent call last):
  File "main.py", line 156, in <module>
    homography_matrices, kps_court = court_detector.infer_model(frames)
  File "/content/TennisProject/court_detection_net.py", line 47, in infer_model
    x_pred, y_pred = refine_kps(image, int(y_pred), int(x_pred), crop_size=40)
  File "/content/TennisProject/postprocess.py", line 31, in refine_kps
    inters = line_intersection(lines[0], lines[1])
  File "/content/TennisProject/postprocess.py", line 13, in line_intersection
    point = intersection[0].coordinates if len(intersection) > 0 else None
AttributeError: 'Line2D' object has no attribute 'coordinates'
```

Can you please guide me on this?

**Comment by yastrebksv** [comment]
Which version of sympy are you using?

**Comment by cesarmart** [comment]
Hi yastrebksv! 
I'm having the same issue in postprocessing: AttributeError: 'Line2D' object has no attribute 'coordinates' at the same line.
I have a fresh install of everything, so I used the requirements.txt for package versions.
Maybe I have to update sympy? thanks

**Comment by cesarmart** [comment]
Quick update: I printed it out the interesections found and the problem arises when instead of a Point2D the intersection found is a Line2D, which doesn't have the coordinates property.

**Comment by mafiat** [comment]
i am getting the same error. and solution here?

**Comment by yastrebksv** [comment]
I fixed this issue in this commit https://github.com/yastrebksv/TennisProject/commit/b7552e955253c008c7612298cb40694682a74ef9
